### ISSUE TITLE
Multiple Ideas

### ISSUE THREAD

**Issue by FossiiLs** [ExpDev07/legacy-rp-cad#2]
1. Not sure if this is possible but let's say someone wants to act as dispatch. They can select a Trooper and assign them to a call. May need to be able to click on a blip on the map which will show the troopers name to see which Trooper is in the area that a call comes in to be assigned.

2. Be able to enter that you have given someone a warning for speeding etc. If you gave someone a fine you can list how much they were fined for and what they were fined for.

3. Be able to type the arrest reports within the MDT/CAD and have them be easily view able to the command team.

4. Have it show what licenses civilians have, whether they be Driver Licenses, Weapons Licenses, etc. 

5. When a Trooper has arrested someone, have a drop down box or something to the effect to show what was confiscated by the Trooper.

**Comment by ExpDev07** [comment]
> Not sure if this is possible but let's say someone wants to act as dispatch. They can select a Trooper and assign them to a call. May need to be able to click on a blip on the map which will show the troopers name to see which Trooper is in the area that a call comes in to be assigned.

This is very much possible, however, a dispatch role has been discussed before but not gotten anywhere. Seems like an awful lot to implement a full dispatch system without anyone wanting to use it.

> Be able to enter that you have given someone a warning for speeding etc. If you gave someone a fine you can list how much they were fined for and what they were fined for.

Where would this go? Under fines? Just that it says 0$ and "warning" instead, or would there be a seperate "warnings" system?

> Be able to type the arrest reports within the MDT/CAD and have them be easily view able to the command team.

Arrest reports are a must :) Good idea.

> Have it show what licenses civilians have, whether they be Driver Licenses, Weapons Licenses, etc.

Also a good idea and  a must -- should it also give the option to revoke the licenses or just view?

> When a Trooper has arrested someone, have a drop down box or something to the effect to show what was confiscated by the Trooper.

Would this go under the arrest report or be its seperate thing?

**Comment by samsn8** [comment]
GSR test, An In game MDT would also be so fucking cool and helpfula

**Comment by ExpDev07** [comment]
Seperated into multiple tickets: https://github.com/ExpDev07/legacy-rp-cad/issues/3, https://github.com/ExpDev07/legacy-rp-cad/issues/4, https://github.com/ExpDev07/legacy-rp-cad/issues/5, https://github.com/ExpDev07/legacy-rp-cad/issues/6.
